FROM alpine:latest

# Mise à jour et installation du serveur web Nginx
RUN apk update && \
	apk add --no-cache nginx && \
	rm -rf /var/cache/apk/*

# Création d'une page HTML simple comme preuve de déploiement
RUN mkdir -p /var/www/localhost && \
	echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/localhost/index.html

# Expose le port par défaut de Nginx
EXPOSE 80

# Démarre Nginx en mode non-démonisé
CMD ["nginx", "-g", "daemon off;"]
